spring:
  application:
    name: regedit-service
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        default_schema: SV_REGEDIT
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(LOAD_BALANCE=on)(ADDRESS=(PROTOCOL=TCP)(HOST=dm05-scan.istat.it)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=CRO1C)))
    username: UP_IANNACONE[SV_REGEDIT]
    password: 
    driverClassName: oracle.jdbc.OracleDriver
    platform: oracle
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
server:
  port: 8081

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8080/eureka
    instance:
      hostname: localhost
management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics, auditevents
  metrics:
    export:
      atlas:
        enabled: false
api:
  version: 1

security:
  secret-key: is2-secretkey
  
app:
  editing:
    backup: true  
    Rserver: rstudio8.istat.it
    Ruser: ruser
    Rpass: Ruser2023
    Rwd: //home2//ruser
    Rport: 6311

