language: java
sudo: true
jdk: openjdk11
 # would just use default install/script but the ./mvnw script errors on travis
# obviously this only works for maven builds right now...
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
before_install:
  - chmod +x mvnw
